name: Run Test
on:
  pull_request:
    branches:
      - assignment-1
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: docker compose -f docker-compose.test.yaml build

      - name: Run pytest
        run: docker compose -f docker-compose.test.yaml run test